import "./globals.css"
import type { Metadata } from "next"
import { Archivo } from "next/font/google"
import { NextFont } from "next/dist/compiled/@next/font"
import { ConditionalHeader } from "@/providers/conditionalHeader"
import { ConditionalFooter } from "@/providers/conditionalFooter"
import { RefreshProvider } from "@/providers/RefreshToken.provider"
import { QueryClintProvider } from "@/providers/queryclient.provider"

const archivo: NextFont= Archivo();
export const metadata: Metadata= {
  title: "German W M",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased scroll-smooth bg-slate-100 min-h-screen w-full flex flex-col ${archivo.className}`}>
        <QueryClintProvider>
          <RefreshProvider>
            <div className="flex flex-col min-h-screen w-full">
              <ConditionalHeader/>
              <main className="flex-grow w-full">
                {children}
              </main>
              <ConditionalFooter/>
            </div>
          </RefreshProvider>
        </QueryClintProvider>
      </body>
    </html>
  )
}