import "./globals.css"
import type { Metadata } from "next"
import { Archivo } from "next/font/google"
import { NextFont } from "next/dist/compiled/@next/font"
import { ConditionalHeader } from "@/providers/conditionalHeader"
import { ConditionalFooter } from "@/providers/conditionalFooter"
import { RefreshProvider } from "@/providers/RefreshToken.provider"
import { QueryClintProvider } from "@/providers/queryclient.provider"

const archivo: NextFont= Archivo();
export const metadata: Metadata= {
  title: "German W M",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={`antialiased scroll-smooth bg-slate-100  ${archivo.className}`}>
        <QueryClintProvider>
          <RefreshProvider>
              <ConditionalHeader/>
                <div className="max-w-[100rem] mx-auto">
                  {children}
                </div>
              <ConditionalFooter/>
          </RefreshProvider>
        </QueryClintProvider>
      </body>
    </html>
  )
}