import "./globals.css"
import type { Metadata } from "next"
import { Archivo } from "next/font/google"
import { NextFont } from "next/dist/compiled/@next/font"
import { ConditionalHeader } from "@/providers/conditionalHeader"
import { ConditionalFooter } from "@/providers/conditionalFooter"
import { QueryClintProvider } from "@/providers/queryclient.provider"
import Hero from "@/components/Hero"

const archivo: NextFont= Archivo();
export const metadata: Metadata= {
  title: "German W M",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased scroll-smooth bg-slate-100 ${archivo.className}`}
      >
        <QueryClintProvider>
          <ConditionalHeader/>
            {children}
            <Hero/>
          <ConditionalFooter/>
        </QueryClintProvider>
      </body>
    </html>
  )
}
