import "./globals.css"
import type { Metadata } from "next"
import { Archivo } from "next/font/google"
import { Header } from "@/components/Header"
import { NextFont } from "next/dist/compiled/@next/font";

const archivo: NextFont= Archivo();
export const metadata: Metadata= {
  title: "Home Page",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-100 ${archivo.className}`}
      >
        <Header/>
        <div className="max-w-[1600px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  )
}
