import "./globals.css"
import type { Metadata } from "next"
import { Rubik } from "next/font/google"
import { Header } from "@/components/Header"

const rubikSans= Rubik({
  variable: "--font-rubik-sans",
  subsets: ["latin"]
})

export const metadata: Metadata= {
  title: "Landing Page",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikSans.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  )
}
